// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCm0FvQ9vqb0Mpt_gI6GsgXnZ2Eswj32aA',
    appId: '1:725700398220:web:a10950a873774e6ff9bfa9',
    messagingSenderId: '725700398220',
    projectId: 'sleepy-car',
    authDomain: 'sleepy-car.firebaseapp.com',
    storageBucket: 'sleepy-car.firebasestorage.app',
    measurementId: 'G-VSD873KRFW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkaNxqOHdrbGdz4Jui_GwTPAUsxlAcGis',
    appId: '1:725700398220:android:c8a14f9fb955387bf9bfa9',
    messagingSenderId: '725700398220',
    projectId: 'sleepy-car',
    storageBucket: 'sleepy-car.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDT4U-_g-7O3SCkA32ru477Pb4jFT9jlXo',
    appId: '1:725700398220:ios:5fe03f604614b717f9bfa9',
    messagingSenderId: '725700398220',
    projectId: 'sleepy-car',
    storageBucket: 'sleepy-car.firebasestorage.app',
    iosBundleId: 'com.example.sleepy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDT4U-_g-7O3SCkA32ru477Pb4jFT9jlXo',
    appId: '1:725700398220:ios:5fe03f604614b717f9bfa9',
    messagingSenderId: '725700398220',
    projectId: 'sleepy-car',
    storageBucket: 'sleepy-car.firebasestorage.app',
    iosBundleId: 'com.example.sleepy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCm0FvQ9vqb0Mpt_gI6GsgXnZ2Eswj32aA',
    appId: '1:725700398220:web:9e32845f6d8935aff9bfa9',
    messagingSenderId: '725700398220',
    projectId: 'sleepy-car',
    authDomain: 'sleepy-car.firebaseapp.com',
    storageBucket: 'sleepy-car.firebasestorage.app',
    measurementId: 'G-DSZR8QPX7N',
  );
}
